sonar.projectKey=AGES-RFID_frontend
sonar.organization=ages-rfid

sonar.sources=src
sonar.tests=src,test

sonar.test.inclusions=**/*.spec.ts, **/*.spec.tsx, test/**
sonar.exclusions=**/*.spec.ts, **/*.spec.tsx, node_modules/**, dist/**, build.ts, bunfig.toml, biome.json, commitlint.config.js, src/types.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
