name: Tag Release (Production)

on:
  push:
    tags: ["v*"]

permissions:
  id-token: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  gitlab-sync:
    name: GitLab Sync
    uses: AGES-RFID/cicd/.github/workflows/gitlab-sync.yml@main
    secrets:
      gitlab_token: ${{ secrets.GITLAB_TOKEN }}

  continuous-integration:
    name: Continuous Integration Production
    uses: AGES-RFID/cicd/.github/workflows/ci-bun.yml@main
    with:
      environment: "production"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  continuous-deployment:
    name: Continuous Deployment Production
    needs: [continuous-integration]
    uses: AGES-RFID/cicd/.github/workflows/cd-s3-cloudfront.yml@main
    with:
      environment: "production"
      version: ${{ github.ref_name }}
      role-to-assume: "arn:aws:iam::507099298238:role/ages-rfid-cicd-role"
    secrets: inherit
