name: Tag Release (Production)

on:
  push:
    tags: ["v*"]

permissions:
  id-token: write
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  ci-build:
    name: CI & Build (Production)
    uses: AGES-RFID/cicd/.github/workflows/ci-bun.yml@main
    with:
      environment: "production"
    secrets: inherit

  cd-deploy:
    name: CD (Production)
    needs: [ci-build]
    uses: AGES-RFID/cicd/.github/workflows/cd-s3-cloudfront.yml@main
    with:
      environment: "production"
      role-to-assume: "arn:aws:iam::507099298238:role/ages-rfid-cicd-role"
    secrets: inherit
